import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
const MAX_OUTPUT=64*1024, wait=ms=>new Promise(r=>setTimeout(r,ms));
const exists=pid=>{if(!pid)return false;try{process.kill(-pid,0);return true;}catch(e){return e.code!=='ESRCH';}};
export class LocalAdapter {
 constructor(){this.runs=new Map();}
 start(spec){let child;try{child=spawn(spec.command,spec.args??[],{stdio:['ignore','pipe','pipe'],detached:true});}catch(e){return Promise.reject(e);}const r={id:randomUUID(),child,pid:child.pid,state:'running',closed:false,out:'',err:''};this.runs.set(r.id,r);const add=(k,d)=>{r[k]+=d.toString().slice(0,Math.max(0,MAX_OUTPUT-r[k].length));};child.stdout.on('data',d=>add('out',d));child.stderr.on('data',d=>add('err',d));r.done=new Promise(resolve=>{child.once('error',e=>{r.error=e;r.state='failed';resolve();});child.once('close',(code,signal)=>{r.closed=true;r.code=code;r.signal=signal;if(r.state!=='stopped')r.state=code===0?'completed':'failed';resolve();});});return Promise.resolve({id:r.id});}
 async status(id){const r=this.runs.get(id);if(!r)throw Error('unknown-run');return {state:r.state};}
 async result(id){const r=this.runs.get(id);if(!r)throw Error('unknown-run');if(!r.closed||['running','canceling'].includes(r.state))throw Error('result-not-ready');await r.done;return {output:r.out,error:r.err|| (r.error ? `spawn failed: ${r.error.code||'process error'}` : ''),code:r.code,signal:r.signal};}
 async cancel(id){const r=this.runs.get(id);if(!r)return {supported:false};if(!exists(r.pid)&&r.closed){r.state='stopped';return {supported:true,stopped:true};}r.state='canceling';try{if(r.pid)process.kill(-r.pid,'SIGTERM');}catch(e){if(e.code!=='ESRCH')throw e;}let end=Date.now()+500;while(exists(r.pid)&&Date.now()<end)await wait(20);if(exists(r.pid)){try{process.kill(-r.pid,'SIGKILL');}catch(e){if(e.code!=='ESRCH')throw e;}end=Date.now()+500;while(exists(r.pid)&&Date.now()<end)await wait(20);}const done=Promise.race([r.done,wait(250)]);await done;const stopped=!exists(r.pid)&&r.closed;r.state=stopped?'stopped':'failed';return stopped ? {supported:true,stopped:true} : {supported:true,stopped:false,error:'process-group-did-not-stop'};}
}
// Independent deterministic in-memory double; never launches a process.
export class FakeAdapter {constructor(capabilities={cancel:true}){this.capabilities=capabilities;this.runs=new Map();}async start(s={}){const id=randomUUID();this.runs.set(id,{state:s.fail?'failed':'completed',output:s.output??'',error:s.fail?(s.error??'fake failure'):'',code:s.fail?1:0});return {id};}async status(id){const r=this.runs.get(id);if(!r)throw Error('unknown-run');return {state:r.state};}async result(id){const r=this.runs.get(id);if(!r)throw Error('unknown-run');return {output:r.output,error:r.error,code:r.code};}async cancel(id){if(!this.capabilities.cancel||!this.runs.has(id))return {supported:false};this.runs.get(id).state='stopped';return {supported:true,stopped:true};}}
export function conform(adapter){return ['start','status','result','cancel'].filter(name=>typeof adapter[name]!=='function');}
