import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {mkdtemp,rm,stat,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import pg from 'pg';
import {DurableCoordinationRegistry} from './durable-registry.mjs';
import {exportNamespace,restoreNamespace} from './backup.mjs';
import {inspectRecovery} from './recovery-inspection.mjs';
const config=JSON.parse(readFileSync(new URL('../../.local/config.json',import.meta.url)));
const exec=promisify(execFile);
test('BACKUP-01/02 restore complete state into new namespace; duplicate remains duplicate; authority not transferred',async t=>{
  const pool=new pg.Pool({connectionString:config.databaseUrl});
  const source='backup-'+randomUUID(),target='restore-'+randomUUID(),cliTarget='cli-'+randomUUID();
  const dir=await mkdtemp(join(tmpdir(),'coord-backup-'));
  t.after(async()=>{try{for(const table of ['events','receipts','grants','namespaces'])await pool.query('DELETE FROM coordination.'+table+' WHERE namespace_id=ANY($1)',[[source,target,cliTarget]]);}finally{await pool.end();await rm(dir,{recursive:true,force:true});}});
  const r=new DurableCoordinationRegistry({pool,namespace:source});await r.init();
  const baseline='b'.repeat(40),g={taskId:'BACKUP-001',workerId:'w',generation:1,recordVersion:1,packetRevision:1,contracts:{backup:'1'},baseline,ownedPaths:['src/'],requiredObligations:['B1'],state:'running',budget:{maxMinutes:1,billing:'no-paid-api'},checkpointMinutes:1,testResources:['node']};
  const s={submissionId:'receipt-1',taskId:g.taskId,workerId:'w',generation:1,recordVersion:1,packetRevision:1,contracts:g.contracts,baseline,artifactRevision:baseline,artifactLocation:'git:'+baseline,changedPaths:['src/a'],checks:[{obligation:'B1',command:'test',environment:'local',testedRevision:baseline,startedAt:'2026-01-01T00:00:00Z',endedAt:'2026-01-01T00:01:00Z',outcome:'pass',evidenceLocation:'local'}],unrunChecks:[],limitations:[]};
  await r.grant(g,0);await r.submit(s);
  const backup=await exportNamespace(pool,source);
  assert.equal(backup.data.receipts.length,1);
  assert.equal((await restoreNamespace(pool,backup,target)).authority,'not-transferred');
  const restored=new DurableCoordinationRegistry({pool,namespace:target});
  assert.equal((await restored.submit(s)).status,'duplicate');
  assert.equal((await inspectRecovery({pool,namespace:target})).interrupted.length,1);
  await assert.rejects(()=>restored.reassign(g.taskId,{...g,workerId:'new'},{},2),/termination/);
  await assert.rejects(()=>restoreNamespace(pool,backup,target)); // no overwrite
  await assert.rejects(()=>restoreNamespace(pool,backup,source),/new-destination/);
  const corrupt=structuredClone(backup);corrupt.data.revision++;
  await assert.rejects(()=>restoreNamespace(pool,corrupt,'corrupt-'+randomUUID()),/checksum/);
  assert.deepEqual((await exportNamespace(pool,target)).data.receipts,backup.data.receipts);
  assert.equal((await r.snapshot()).revision,2);
  const file=join(dir,'backup.json'),env={...process.env,COORDINATION_DATABASE_URL:config.databaseUrl};
  const cli=(...args)=>exec(process.execPath,['contracts/coordination/backup-cli.mjs',...args],{env,timeout:15000});
  await cli('export',source,file);
  assert.equal((await stat(file)).mode & 0o777,0o600);
  const original=await readFile(file,'utf8');
  await assert.rejects(()=>cli('export',source,file));
  assert.equal(await readFile(file,'utf8'),original);
  assert.equal(JSON.parse((await cli('restore',cliTarget,file)).stdout).authority,'not-transferred');
  assert.equal((await new DurableCoordinationRegistry({pool,namespace:cliTarget}).submit(s)).status,'duplicate');
});
