import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CoordinationRegistry} from './registry.mjs';

const rev='a'.repeat(40);
const grant={taskId:'T-1',workerId:'worker-1',generation:1,recordVersion:1,packetRevision:1,contracts:{catalog:'1.0'},baseline:rev,ownedPaths:['pilot/'],requiredObligations:['PUB-01'],state:'running',budget:{maxMinutes:10,billing:'no-paid-api'},checkpointMinutes:5,testResources:['node']};
const submission={submissionId:'S-1',taskId:'T-1',workerId:'worker-1',generation:1,recordVersion:1,packetRevision:1,contracts:{catalog:'1.0'},baseline:rev,artifactRevision:rev,artifactLocation:'git:'+rev,changedPaths:['pilot/a.ts'],checks:[{obligation:'PUB-01',command:'test',environment:'local',testedRevision:rev,startedAt:'2026-09-12T00:00:00Z',endedAt:'2026-09-12T00:01:00Z',outcome:'pass',evidenceLocation:'evidence/a'}],unrunChecks:[],limitations:[]};
test('rejects malformed grants before mutation',()=>{const r=new CoordinationRegistry();assert.throws(()=>r.grant({...grant,budget:undefined}));assert.deepEqual(r.events(),[]);});
test('same identity cannot silently replace the owned scope',()=>{const r=new CoordinationRegistry();r.grant(grant);assert.throws(()=>r.grant({...grant,ownedPaths:['elsewhere/']}),/conflict/);});
test('overlapping tasks cannot claim parent or child paths',()=>{for(const ownedPaths of [['pilot/a.ts'],['pilot/modules/']]){const r=new CoordinationRegistry();r.grant(grant);assert.throws(()=>r.grant({...grant,taskId:'T-2',workerId:'w2',ownedPaths}),/conflict/);}});
test('grant rejects traversal paths',()=>{const r=new CoordinationRegistry();assert.throws(()=>r.grant({...grant,ownedPaths:['pilot/../other/']}));});
test('directory-like exact path cannot overlap descendant allocation',()=>{const r=new CoordinationRegistry();r.grant({...grant,ownedPaths:['pilot']});assert.throws(()=>r.grant({...grant,taskId:'T-2',ownedPaths:['pilot/a.ts']}),/conflict/);});
test('reassignment needs explicit confirmation and validates before cancelling',()=>{const r=new CoordinationRegistry();r.grant(grant);assert.throws(()=>r.reassign('T-1',{...grant,workerId:'new'}),/termination/);assert.equal(r.submit(submission).status,'accepted-for-review');});
test('invalid replacement leaves old grant intact',()=>{const r=new CoordinationRegistry();r.grant(grant);assert.throws(()=>r.reassign('T-1',{...grant,ownedPaths:['../']},{stopped:true,workerId:'worker-1',generation:1,evidence:'process receipt'}),/invalid-grant/);assert.equal(r.submit(submission).status,'accepted-for-review');assert.equal(r.events()[0].sequence,1);});
test('stale termination receipt cannot authorize a newer generation',()=>{const r=new CoordinationRegistry();r.grant(grant);const receipt={stopped:true,workerId:'worker-1',generation:1,evidence:'receipt'};r.reassign('T-1',{...grant,workerId:'new'},receipt);assert.throws(()=>r.reassign('T-1',{...grant,workerId:'third'},receipt),/termination/);});
test('returned event edits cannot mutate registry history',()=>{const r=new CoordinationRegistry();r.grant(grant);r.events()[0].payload.ownedPaths.push('anything/');assert.deepEqual(r.events()[0].payload.ownedPaths,['pilot/']);});
test('registry records grant and accepts a valid submission for review',()=>{const r=new CoordinationRegistry(()=>new Date('2026-09-12T01:00:00Z'));r.grant(grant);assert.equal(r.submit(submission).status,'accepted-for-review');assert.equal(r.events().length,2);});
test('registry rejects stale generations and conflicting duplicate IDs',()=>{const r=new CoordinationRegistry();r.grant(grant);assert.equal(r.submit({...submission,generation:2}).status,'rejected');assert.equal(r.submit(submission).status,'accepted-for-review');assert.equal(r.submit({...submission,limitations:['changed']}).status,'rejected');});
